apiVersion: v1
kind: Pod
metadata:
  name: miniotest
  labels:
    app: miniotest
spec:
  volumes:
  - name: datatest
    persistentVolumeClaim:
      claimName: miniotest-pv-claim
  containers:
  - name: miniotest
    volumeMounts:
    - name: datatest
      mountPath: "/data"
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    command: ["bin/sh", "-c"]
    args: ["mkdir /data/bucket; minio server /data"]
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
    readinessProbe:
      httpGet:
        path: /minio/health/ready
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /minio/health/live
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniotest-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: miniotest-svc
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: miniotest


---
apiVersion: v1
kind: Pod
metadata:
  name: pyboto3test
  labels:
    app: pyboto3test
spec:
  volumes:
  - name: config
    hostPath:
      path: /home/t.kozuka/proj/analytics/lakefs
  containers:
  - name: pyboto3test
    volumeMounts:
    - name: config
      mountPath: /etc/lakefs
      readOnly: false
    image: lakefs/boto3:latest
    command: ['tail', '-f', '/dev/null']
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    readinessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5
    livenessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pyboto3-svc
spec:
  selector:
    app: pyboto3test
  ports:
  - port: 8000
  type: NodePort