apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: minio-pv-claim
  containers:
  - name: minio
    volumeMounts:
    - name: data 
      mountPath: "/data"
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    command: ["bin/sh", "-c"]
    args: ["mkdir /data/bucket; minio server /data"]
    env:
    - name: MINIO_ACCESS_KEY
      value: "minio"
    - name: MINIO_SECRET_KEY
      value: "minio123"
    ports:
    - containerPort: 9000
    readinessProbe:
      httpGet:
        path: /minio/health/ready
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /minio/health/live
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio


---
apiVersion: v1
kind: Pod
metadata:
  name: pyboto3
  labels:
    app: pyboto3
spec:
  volumes:
  - name: config
    hostPath:
      path: /run/desktop/mnt/host/c/Users/kozuka/Documents/study/kubernetes/pyboto3
  containers:
  - name: pyboto3
    volumeMounts:
    - name: config
      mountPath: /src
      readOnly: true
    image: pyboto3:latest
    command: ['tail', '-f', '/dev/null']
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    readinessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5
    livenessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5

  - name: python
    volumeMounts:
    - name: config
      mountPath: /src
      readOnly: true
    image: nginx:latest
    command: ['tail', '-f', '/dev/null']
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
    readinessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5
    livenessProbe:
      exec:
        command: ['bash']
      initialDelaySeconds: 5
      timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pyboto3-svc
spec:
  selector:
    app: pyboto3
  ports:
  - port: 8000
  type: NodePort